import { Open_Sans } from 'next/font/google';
import '../styles/helper.scss';

const openSans = Open_Sans({
  weight: ['300', '500', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Aníbal González',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${openSans.className}`}>{children}</body>
    </html>
  );
}
